on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint - Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22 ]
    steps:
    - uses: actions/checkout@v4.2.1
    - uses: actions/setup-node@v4.0.4
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: npm install
    - run: npm test
